In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import GridSearchCV, StratifiedShuffleSplit
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from scipy.special import entr
from sklearn import preprocessing
import matplotlib.pyplot as plt

import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from IPython.display import display
import itertools
from itables import init_notebook_mode
import random
init_notebook_mode(all_interactive=True)

<IPython.core.display.Javascript object>

In [2]:
def generate_features(mouse_raw):
    horiz_spd = mouse_raw['x'].diff()/mouse_raw['timestamp'].diff()
    vert_spd = mouse_raw['y'].diff()/mouse_raw['timestamp'].diff()
    tang_spd = np.sqrt((horiz_spd**2)+(vert_spd**2))

    horiz_acc = horiz_spd.diff()/mouse_raw['timestamp'].diff()
    vert_acc = vert_spd.diff()/mouse_raw['timestamp'].diff()
    tang_acc = np.sqrt((horiz_acc**2)+(vert_acc**2))


    return { 'horiz_spd': horiz_spd, 'vert_spd': vert_spd, 'tang_spd':tang_spd, 
            'horiz_acc': horiz_acc, 'vert_acc': vert_acc,  
            'tang_acc': tang_acc, 'mouse_rawx_diff': mouse_raw['x'].diff(), 'mouse_rawx_timestamp': mouse_raw['timestamp'].diff()}

def ranges(x):
    #print(x.max() - x.min())
    return x.max() - x.min()
def rmssd(x):
    return np.sqrt(np.mean(np.diff(x) ** 2))
def sdsd(x):
    return st.stdev(np.diff(x))
def nni_50(x):
    return  sum(np.abs(np.diff(x)) > 50)

def pnni_50(x):
    return 100 * nni_50(x) / len(x)

def nni_20(x):
    return sum(np.abs(np.diff(x)) > 20)

def pnni_20(x):
    return  100 * nni_20(x) / len(x)

def nni_5(x):
    return sum(np.abs(np.diff(x)) > 5)

def avg_hr(x):
    return  st.mean(100/x)

def avg_hr(x):
    return  st.mean(60000/x)
def std_hr(x):
    return  st.stdev(60000/x)
def min_hr(x):
    return  min(60000/x)
def max_hr(x):
    return  max(60000/x)

def energy(x):
    return sum(np.square(x))
def abs_sum_diff(x):
    return sum(np.abs(np.diff(x)))

In [18]:
#os.chdir('../')

In [3]:
os.listdir()

['3_mouse.bin',
 '.DS_Store',
 '5_mouse.bin',
 'Untitled.ipynb',
 '2_mouse.bin',
 'datasets',
 '4_mouse.bin',
 '.gitignore',
 '1_mouse.bin',
 '.ipynb_checkpoints',
 'boun_d.ipynb',
 'testing.csv',
 '.git']

In [16]:
os.chdir('./datasets')
arr = os.listdir()
files_dict = {}


for i in arr:
    #print(i)
    print(i)
    if i == ".DS_Store":
        continue
    os.chdir(i)

    arr2 = os.listdir()
    print(len(arr2))
    #print(arr2)
    #print(len(arr2))
    #print(i)
    if len(arr2) != 0:#'./training' in arr2: len(arr2) != 0:
        #w = '/content/drive/MyDrive/boun dataset/'+ str(i) + '/training'
        print(arr2)
        w = './training'
        os.chdir(w)
        arr3 = os.listdir()
        files_dict[i] = arr3
        #print(w)
        #print(arr3)
        #print("----")
        os.chdir('../')

    os.chdir('../')
    print(os.listdir())


os.chdir('../')

1
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
10
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
11
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
12
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
13
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
14
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
15
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
16
1
['training']
['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '3', '4', '5', '6', '7', '8', '9']
17
1
['tr

In [5]:
os.listdir()

['.DS_Store',
 '.git',
 '.gitignore',
 '.ipynb_checkpoints',
 '1_mouse.bin',
 '2_mouse.bin',
 '3_mouse.bin',
 '4_mouse.bin',
 '5_mouse.bin',
 'boun_d.ipynb',
 'datasets',
 'testing.csv',
 'Untitled.ipynb']

In [17]:
user_dict = {}
user_dict_by_category = {}
all_category = ['office\n', 'file system\n', 'browsing\n', 'gaming\n', 'entertainment\n', 'development\n']
for i in list(files_dict.keys()):
    user_dict[i] = []
    user_dict_by_category[i] = {}
    for category in all_category:
        user_dict_by_category[i][category] = []
    
    #count = 1
    for j in list(files_dict[i]):

        #user_dict[i][count] = None
        w = './datasets/' + i + '/training/' + j
        file1 = open(w, 'r')
        Lines = file1.readlines()
        txt_array = []
        for k in range(0, len(Lines)):
            #print(Lines[k].split(","))
            txt_array.append(Lines[k].split(","))

        tmpp = pd.DataFrame(txt_array[1:], columns=txt_array[0])
        tmpp['timestamp'] = [int(i[0])*1000 + int(str(i[1])[:3].ljust(3, '0')) for i in tmpp['client_timestamp'].str.split('.')]
        uniquess = tmpp['window\n'].unique().tolist()
#        print(uniquess)
        tmpp = tmpp[tmpp['window\n'] == 'browsing\n']
        user_dict[i].append(tmpp)
        for k in all_category:
            tmpp = tmpp[tmpp['window\n'] == k]
            #tmpp = tmpp[tmpp['state'] == "Move"]
            if tmpp.empty:
                user_dict_by_category[i][k].append(tmpp)
            #count = count + 1


In [18]:
movement = {}

for i in list(user_dict.keys()):#[2:3]:#[:2]:
    movement[i] = []
    #for j in range(0, 5):
    for j in range(0, len(user_dict[i])):
        tt = user_dict[i][j]
        #print(tt)
        df = pd.DataFrame(tt, columns=tmpp.columns)
        #df = df[df["button"] == "MOVE"]
        #df['timestamp_mili'] = [int(i[0])*1000 + int(i[1]) for i in df['client_timestamp'].str.split('.')]
        movement[i].append(df)


In [ ]:
movement = {}

for i in list(user_dict_by_category[].keys()):#[2:3]:#[:2]:
    movement[i] = []
    #for j in range(0, 5):
    for j in range(0, len(user_dict[i])):
        tt = user_dict[i][j]
        #print(tt)
        df = pd.DataFrame(tt, columns=tmpp.columns)
        #df = df[df["button"] == "MOVE"]
        #df['timestamp_mili'] = [int(i[0])*1000 + int(i[1]) for i in df['client_timestamp'].str.split('.')]
        movement[i].append(df)


In [53]:
for i in list(movement.keys())[1:2]:
    for k in range(0, 1):
        df2 = pd.DataFrame(movement[i][k], columns=tmpp.columns)
df2.loc[25559:25560]

client_timestamp     x    y button     state    window\n      timestamp
25559   1573627385.559  1339  697   Left   Pressed  browsing\n  1573627385559
25560   1573627385.696  1339  697   Left  Released  browsing\n  1573627385696

In [19]:
import random
click_features = {}
problematic = {}
for i in list(movement.keys()):
    click_features[i] = []
    problematic[i] = []
    #print(i)
    print("User: ",i)
    for k in range(0, len(movement[i])):#[3:4]:#[5:6]:
        #print("session index: ", k)
    #for k in range(0, 1):

    #for k in range(0, 1):#[3:4]:#[5:6]:
  
        df = pd.DataFrame(movement[i][k], columns=tmpp.columns)
        df.to_csv("testing.csv")
        tt = pd.read_csv("testing.csv")
        
#        tt.reset_index(drop=False, inplace=True)

        zz1 = tt[((tt["state"] == "Pressed")| (tt["state"] == "Released")) & (tt['button'] == "Left")]
        zz1_p = zz1[zz1["state"] == "Pressed"]
        zz1_r = zz1[zz1["state"] == "Released"]
        
        tt.set_index("Unnamed: 0", inplace=True)
        
        pressed_indexes = zz1_p['Unnamed: 0']
        released_indexes = zz1_r['Unnamed: 0']

        list1 = list(pressed_indexes)
        list2 = list(released_indexes)
        
        list1_consecutive = []
        list2_consecutive = []
        
        # iterate over all possible pairs of indexes and exclude any pairs that are too close together

        for u in range(min(len(list1), len(list2))):
            if list2[u] == list1[u] + 1:
                list1_consecutive.append(list1[u])
                list2_consecutive.append(list2[u])
        
        #print(list1_consecutive)
        #print(list2_consecutive)
        if len(list1_consecutive) != len(list2_consecutive):
            print("Error")
        
        print(len(list1_consecutive))
        
        for kk in range(0, len(list1_consecutive)):
            res = tt.loc[list2_consecutive[kk]]['timestamp'] - tt.loc[list1_consecutive[kk]]['timestamp']
            if (res > 0) and (res < 1000):
                click_features[i].append(res)
            else:
                print("The value is ")
                print(res)
                print("list1_consecutive[kk]")
                print(list1_consecutive[kk])
                print("tt.iloc[list1_consecutive[kk]]['timestamp']")
                print(tt.loc[list1_consecutive[kk]]['timestamp'])
                problematic[i].append(list1_consecutive[kk])
                print("Problematic value", str(res))

    print(click_features[i])
    print("This is the length of clicks for user", i)
    print(len(click_features[i]))
    print("-------")
print(problematic)

zz1.set_index("Unnamed: 0", inplace=True)
#zz1.loc[25559:(25559+1000)]
#tt.loc[25559]
#1573627385696 - 1573627385559

User:  1
414
1132
814
668
303
1058
33
859
The value is 
1158
list1_consecutive[kk]
117863
tt.iloc[list1_consecutive[kk]]['timestamp']
1569608391985
Problematic value 1158
128
77
[53, 48, 97, 7, 29, 18, 111, 21, 72, 148, 76, 154, 168, 138, 216, 119, 153, 117, 152, 125, 160, 159, 181, 145, 166, 153, 145, 126, 189, 140, 182, 167, 152, 161, 163, 156, 145, 154, 120, 125, 140, 145, 77, 66, 141, 132, 112, 118, 83, 125, 113, 111, 97, 91, 133, 181, 133, 112, 107, 154, 160, 182, 131, 131, 125, 146, 118, 111, 98, 125, 81, 64, 146, 90, 166, 125, 141, 160, 128, 180, 181, 181, 180, 180, 180, 181, 148, 198, 195, 125, 111, 217, 132, 141, 174, 139, 111, 126, 140, 118, 132, 153, 189, 111, 126, 91, 90, 140, 99, 113, 105, 125, 132, 153, 168, 175, 69, 79, 143, 183, 78, 125, 167, 120, 180, 180, 181, 180, 83, 119, 153, 142, 181, 138, 174, 131, 120, 82, 112, 104, 56, 29, 111, 105, 7, 51, 8, 76, 99, 132, 98, 4, 91, 74, 111, 20, 5, 83, 107, 161, 43, 110, 145, 16, 139, 148, 125, 127, 175, 19, 72, 98, 91, 6, 140,

In [ ]:
import random
click_features = {}
problematic = {}
for i in list(movement.keys()):
    click_features[i] = []
    problematic[i] = []
    #print(i)
    print("User: ",i)
    for k in range(0, len(movement[i])):#[3:4]:#[5:6]:
        #print("session index: ", k)
    #for k in range(0, 1):

    #for k in range(0, 1):#[3:4]:#[5:6]:
  
        df = pd.DataFrame(movement[i][k], columns=tmpp.columns)
        df.to_csv("testing.csv")
        tt = pd.read_csv("testing.csv")
        
#        tt.reset_index(drop=False, inplace=True)

        zz1 = tt[((tt["state"] == "Pressed")| (tt["state"] == "Released")) & (tt['button'] == "Right")]
        zz1_p = zz1[zz1["state"] == "Pressed"]
        zz1_r = zz1[zz1["state"] == "Released"]
        
        tt.set_index("Unnamed: 0", inplace=True)
        
        pressed_indexes = zz1_p['Unnamed: 0']
        released_indexes = zz1_r['Unnamed: 0']

        list1 = list(pressed_indexes)
        list2 = list(released_indexes)
        
        list1_consecutive = []
        list2_consecutive = []
        
        # iterate over all possible pairs of indexes and exclude any pairs that are too close together

        for u in range(min(len(list1), len(list2))):
            if list2[u] == list1[u] + 1:
                list1_consecutive.append(list1[u])
                list2_consecutive.append(list2[u])
        
        #print(list1_consecutive)
        #print(list2_consecutive)
        if len(list1_consecutive) != len(list2_consecutive):
            print("Error")
        
        print(len(list1_consecutive))
        
        for kk in range(0, len(list1_consecutive)):
            res = tt.loc[list2_consecutive[kk]]['timestamp'] - tt.loc[list1_consecutive[kk]]['timestamp']
            if (res > 0) and (res < 1000):
                click_features[i].append(res)
            else:
                print("The value is ")
                print(res)
                print("list1_consecutive[kk]")
                print(list1_consecutive[kk])
                print("tt.iloc[list1_consecutive[kk]]['timestamp']")
                print(tt.loc[list1_consecutive[kk]]['timestamp'])
                problematic[i].append(list1_consecutive[kk])
                print("Problematic value", str(res))

    print(click_features[i])
print(problematic)

zz1.set_index("Unnamed: 0", inplace=True)
#zz1.loc[25559:(25559+1000)]
#tt.loc[25559]
#1573627385696 - 1573627385559

In [109]:
df[df['button'] == "Right"]

client_timestamp     x    y button     state    window\n  \
0       1569478466.2489998   255  583   None      Move  browsing\n   
1           1569478466.262   248  553   None      Move  browsing\n   
2           1569478466.274   240  518   None      Move  browsing\n   
3           1569478466.288   235  481   None      Move  browsing\n   
4           1569478466.302   232  446   None      Move  browsing\n   
...                    ...   ...  ...    ...       ...         ...   
228009      1569524060.492  1069   54   None      Move  browsing\n   
228010  1569524060.4989998  1069   54   None      Move  browsing\n   
228011      1569524060.508  1068   54   None      Move  browsing\n   
228012      1569524060.522  1068   54   Left   Pressed  browsing\n   
228013      1569524060.613  1068   54   Left  Released  browsing\n   

            timestamp  
0       1569478466248  
1       1569478466262  
2       1569478466274  
3       1569478466288  
4       1569478466302  
...               ...  
228009  1569524060492  
228010  1569524060498  
228011  1569524060508  
228012  1569524060522  
228013  1569524060613  

[225571 rows x 7 columns]

In [113]:
df.loc[40415:40430]

client_timestamp     x    y button     state    window\n  \
40415      1569490764.835  1231  270   None      Move  browsing\n   
40416  1569490765.0110002  1231  270  Right   Pressed  browsing\n   
40417       1569490765.03  1231  270  Right  Released  browsing\n   
40418  1569490765.3070002  1236  270   None      Move  browsing\n   
40419      1569490765.326  1243  270   None      Move  browsing\n   
40420      1569490765.344  1248  271   None      Move  browsing\n   
40421      1569490765.361  1252  271   None      Move  browsing\n   
40422       1569490765.38  1255  271   None      Move  browsing\n   
40423      1569490765.395  1258  271   None      Move  browsing\n   
40424  1569490765.4120002  1260  272   None      Move  browsing\n   
40425      1569490765.427  1261  272   None      Move  browsing\n   
40426      1569490765.444  1262  272   None      Move  browsing\n   
40427      1569490765.459  1263  272   None      Move  browsing\n   
40428      1569490765.474  1264  272   None      Move  browsing\n   
40429       1569490765.49  1265  272   None      Move  browsing\n   
40430  1569490765.5070002  1265  272   None      Move  browsing\n   

           timestamp  
40415  1569490764835  
40416  1569490765011  
40417  1569490765003  
40418  1569490765307  
40419  1569490765326  
40420  1569490765344  
40421  1569490765361  
40422  1569490765038  
40423  1569490765395  
40424  1569490765412  
40425  1569490765427  
40426  1569490765444  
40427  1569490765459  
40428  1569490765474  
40429  1569490765049  
40430  1569490765507

In [ ]:
click_features

In [86]:
zz1[zz1['button'] == "Right"]

Unnamed: 0  client_timestamp     x    y button     state    window\n  \
90           3709      1.570689e+09    29   24   Left   Pressed  browsing\n   
92           3711      1.570689e+09    28   24   Left  Released  browsing\n   
138          3757      1.570689e+09    61   91   Left   Pressed  browsing\n   
139          3758      1.570689e+09    61   91   Left  Released  browsing\n   
234          3853      1.570689e+09   737   45   Left   Pressed  browsing\n   
...           ...               ...   ...  ...    ...       ...         ...   
19570      866020      1.570743e+09  1522  879   Left  Released  browsing\n   
20876      867326      1.570746e+09  1919    0   Left   Pressed  browsing\n   
20877      867327      1.570746e+09  1919    0   Left  Released  browsing\n   
21008      867458      1.570746e+09  1110  579   Left   Pressed  browsing\n   
21009      867459      1.570746e+09  1110  579   Left  Released  browsing\n   

           timestamp  
90     1570689113534  
92     1570689113644  
138    1570689114797  
139    1570689114092  
234    1570689117095  
...              ...  
19570  1570743260529  
20876  1570746126712  
20877  1570746126088  
21008  1570746128028  
21009  1570746128425  

[397 rows x 8 columns]

In [79]:
# zz = user_dict['1'][0]
# zz1 = zz[(zz["state"] == "Pressed")| (zz["state"] == "Released")]
# zz1_p = zz1[zz1["state"] == "Pressed"]
# zz1_r = zz1[zz1["state"] == "Released"]
# pressed_indexes = zz1_p.index
# released_indexes = zz1_r.index

# list1 = list(pressed_indexes)
# list2 = list(released_indexes)
# # print(released_indexes)
# # print(pressed_indexes)

# threshold = 3

# # create empty lists to store the filtered indexes
# filtered_pressed_indexes = []
# filtered_released_indexes = []
# list1_consecutive = []
# list2_consecutive = []
# # iterate over all possible pairs of indexes and exclude any pairs that are too close together

# for i in range(min(len(list1), len(list2))):
#     if list2[i] == list1[i] + 1:
#         list1_consecutive.append(list1[i])
#         list2_consecutive.append(list2[i])

        
# print(list1_consecutive)
# print(list2_consecutive)
# list1_consecutive[0]
# zz.iloc[list2_consecutive[0]]['timestamp'] - zz.iloc[list1_consecutive[0]]['timestamp']
# #@zz1_p[list2_consecutive[0]] - zz1_r[list1_consecutive[0]]
# # pressed_indexes = np.array(zz22_p_index)
# # released_indexes = np.array(zz22_r_index)

# # # set a threshold for the minimum distance between indexes
# # threshold = 1

# # # find the absolute differences between the indexes
# # diffs = np.abs(pressed_indexes[:, np.newaxis] - released_indexes)

# # # find the valid pairs of indexes
# # valid_pairs = np.argwhere(diffs > threshold)

# # # extract the filtered indexes of Pressed and Released states
# # filtered_pressed_indexes = pressed_indexes[valid_pairs[:, 0]]
# # filtered_released_indexes = released_indexes[valid_pairs[:, 1]]

# # # print the filtered indexes of Pressed and Released states
# # print("Filtered Pressed:", filtered_pressed_indexes)
# # print("Filtered Released:", filtered_released_indexes)


[89, 187, 209, 362, 583, 598, 628, 680, 809, 870, 918, 1221, 1849, 2883, 3186, 3304, 3306, 3308, 3310, 3312, 3314, 3316, 3318, 3320, 3322, 3324, 3326, 3328, 3330, 3332, 3334, 3336, 3338, 3340, 3342, 3344, 3346, 3348, 3350, 3402, 3613, 3678, 3867, 4145, 4158, 4277, 4400, 4559, 4608, 4664, 4719, 4787, 4836, 5060, 5161, 5163, 5397, 5460, 5525, 5664, 5838, 6097, 6310, 6364, 6366, 6368, 6370, 6372, 6374, 6494, 6523, 6581, 6693, 6736, 6801, 6863, 7207, 7448, 7576, 7623, 7667, 7669, 7671, 7673, 7675, 7677, 7702, 7760, 7762, 7764, 7766, 7768, 7770, 7772, 7783, 7785, 7787, 7789, 7791, 7793, 7795, 7797, 7799, 7801, 7803, 7805, 7807, 7809, 7811, 7813, 7815, 7817, 7819, 7821, 7823, 7825, 7916, 7946, 8022, 8551, 8572, 8640, 8734, 8770, 8904, 9064, 9066, 9090, 9187, 9318, 9534, 9650, 10170, 10207, 10275, 10498, 10735, 10904, 11083, 11285, 11477, 11584, 11789, 12146, 12268, 12343, 12556, 12606, 12734, 12870, 13017, 14194, 14274, 14343, 14427, 14544, 14564, 14732, 14820, 15026, 15326, 15478, 15548, 15

53

In [62]:
# import random
# click_features = {}
# for i in list(movement.keys()):#[:1]:
#     click_features[i] = []
#     #print(i)

#     for k in range(0, len(movement[i])):#[3:4]:#[5:6]:

#     #for k in range(0, 1):#[3:4]:#[5:6]:
  
#         df = pd.DataFrame(movement[i][k], columns=tmpp.columns)
#         df.to_csv("testing.csv")
#         tt = pd.read_csv("testing.csv")
#         move_data_down = tt[tt["state"] == "Pressed"]
#         move_data_up = tt[tt["state"] == "Released"]
#         print("===")
#         #print((len(move_data_down)))
#         #print((len(move_data_up)))
#         tt = pd.DataFrame()
#         print("-----")
#         #if (len(move_data_down)) == (len(move_data_up)):
#         for z in range(0, len(move_data_down)):
#             #print(move_data_up['timestamp'].iloc[z] - move_data_down['timestamp'].iloc[z])
#             #print(int(move_data_up['client_timestamp'].str.split('.')[0]) - int((move_data_down['timestamp'].str.split('.')[0])))
#             #print(move_data_up['timestamp'] - move_data_down['timestamp'])
#             tt['Released'] = move_data_up['timestamp']
#             tt['Pressed'] = move_data_down['timestamp']
#             #click_features[i].append(move_data_up['timestamp'].iloc[z] - move_data_down['timestamp'].iloc[z])
#                 #print(random.choice(click_features[i]))

===
-----
===
-----


KeyboardInterrupt: 

In [72]:
aa = pd.concat([move_data_up['timestamp'], move_data_down['timestamp']])
aa

138     1569478468744
295     1569478470924
336     1569478471955
357     1569478480012
399     1569478481005
            ...      
1365    1569523684101
1366    1569527207002
1367    1569531802998
1368    1569523744564
1369    1569524060522
Name: timestamp, Length: 2741, dtype: int64

In [68]:
print(tt.index)
print(move_data_up.index)
print(move_data_down.index)

Int64Index([   138,    295,    336,    357,    399,    447,    743,    879,
              1083,   1266,
            ...
            223029, 223059, 223074, 223090, 223850, 224989, 225053, 225181,
            225370, 225570],
           dtype='int64', length=1371)
Int64Index([   138,    295,    336,    357,    399,    447,    743,    879,
              1083,   1266,
            ...
            223029, 223059, 223074, 223090, 223850, 224989, 225053, 225181,
            225370, 225570],
           dtype='int64', length=1371)
Int64Index([    87,    294,    335,    356,    398,    446,    742,    878,
              1082,   1265,
            ...
            222902, 223058, 223073, 223089, 223849, 224938, 225052, 225180,
            225369, 225569],
           dtype='int64', length=1370)


In [57]:
[move_data_up['timestamp']]

188       1570234810079
355       1570234818032
701       1570234840644
725       1570234841592
787       1570234843784
              ...      
193564    1570319678867
193566    1570319679889
193733    1570319683815
193901    1570319687159
194058    1570319692019
Name: timestamp, Length: 1089, dtype: int64

In [40]:
# #tmpp[tmpp['window\n']== 'browsing\n']
# tmpp[tmpp['state'] != "Move"]

client_timestamp     x    y button     state    window\n  \
3709        1570689113.534    29   24   Left   Pressed  browsing\n   
3710        1570689113.545    28   24   None      Drag  browsing\n   
3711        1570689113.644    28   24   Left  Released  browsing\n   
3757    1570689114.7970002    61   91   Left   Pressed  browsing\n   
3758         1570689114.92    61   91   Left  Released  browsing\n   
...                    ...   ...  ...    ...       ...         ...   
866020      1570743260.529  1522  879   Left  Released  browsing\n   
867326      1570746126.712  1919    0   Left   Pressed  browsing\n   
867327       1570746126.88  1919    0   Left  Released  browsing\n   
867458       1570746128.28  1110  579   Left   Pressed  browsing\n   
867459      1570746128.425  1110  579   Left  Released  browsing\n   

            timestamp  
3709    1570689113534  
3710    1570689113545  
3711    1570689113644  
3757    1570697084002  
3758    1570689114092  
...               ...  
866020  1570743260529  
867326  1570746126712  
867327  1570746126088  
867458  1570746128028  
867459  1570746128425  

[778 rows x 7 columns]

In [38]:
experimenting = user_dict['1'][0]

1570169900000.0

In [39]:


# experimenting['rounded_timestamp'] = np.where(experimenting['timestamp'] < 1000, 0, np.floor(experimenting['timestamp'] / 1000) * 1000)
# experimenting

client_timestamp     x    y button state    window\n      timestamp  \
0           1570169899.971   694  489   None  Move  browsing\n  1570169899971   
1            1570169899.99   703  473   None  Move  browsing\n  1570169899099   
2       1570169900.0089998   713  454   None  Move  browsing\n  1570169900008   
3           1570169900.028   725  436   None  Move  browsing\n  1570169900028   
4           1570169900.046   737  417   None  Move  browsing\n  1570169900046   
...                    ...   ...  ...    ...   ...         ...            ...   
425866       1570232251.22  1785  822   None  Move  browsing\n  1570232251022   
425867      1570232251.231  1789  820   None  Move  browsing\n  1570232251231   
425868      1570232251.242  1790  819   None  Move  browsing\n  1570232251242   
425869      1570232251.252  1791  818   None  Move  browsing\n  1570232251252   
425870  1570232251.2670002  1792  818   None  Move  browsing\n  1570232251267   

        rounded_timestamp  
0            1.570170e+12  
1            1.570170e+12  
2            1.570170e+12  
3            1.570170e+12  
4            1.570170e+12  
...                   ...  
425866       1.570232e+12  
425867       1.570232e+12  
425868       1.570232e+12  
425869       1.570232e+12  
425870       1.570232e+12  

[270110 rows x 8 columns]

In [15]:
np.floor(experimenting['timestamp'].iloc[13] / 1000) * 1000

1570169900000.0

In [21]:
total_array = []

features_array = []
test = []
total_0 = 0
diff = 0
for i in list(movement.keys()):#[:1]:

    #print(i)

    for k in range(0, len(movement[i])):#[3:4]:#[5:6]:

    #for k in range(0, 1):#[3:4]:#[5:6]:

        df = pd.DataFrame(movement[i][k], columns=tmpp.columns)
        df.to_csv("testing.csv")
        tt = pd.read_csv("testing.csv")

        tt = tt[tt["state"] == "Move"]







        proper_a = []
        a = [d for _, d in tt.groupby(tt.index - np.arange(len(tt)))]
        #print(len(a))
        for u in a:
            if len(u) > 200:
                #print(len(u))
                proper_a.append(u)
                
        
        a = proper_a
        #print(len(a))
        for kk in range(0, len(a)):
            features = {}
            features['user'] = i
        #for kk in range(0, 2):

            #if kk == 2:
            #    print(kk)
            xx = pd.DataFrame(a[kk], columns=tmpp.columns)
            xx = xx.drop_duplicates(subset='timestamp', keep='first')
            # xx.to_csv("testing.csv")
            # tt = pd.read_csv("testing.csv")





            xx['x'] = xx['x'].astype(int)
            xx['y'] = xx['y'].astype(int)
            xx['timestamp'] = xx['timestamp'].astype(int)


            b = tt["timestamp"].diff().copy()
            b = b.fillna(0)
            #print(b)
            ind = np.argpartition(b, -len(b))[-len(b):]  
            ind = list(ind)
            count5 = 0
            #print(len(ind))
            #print(ind)
            for yuy in ind:
                #print(count5)
                if count5 < 5:
                    #print(xx[yuy:(yuy + 5)])
                    if not xx[yuy:(yuy+10)].empty:
                        count5 = count5 + 1
                        feature_most_idle = generate_features(xx[yuy:(yuy + 10)])
                        features['mhoriz_spd'] = np.mean(feature_most_idle['horiz_spd'].fillna(0))
                        features['mvert_spd'] = np.mean(feature_most_idle['vert_spd'].fillna(0))
                        features['mtang_spd'] = np.mean(feature_most_idle['tang_spd'].fillna(0))
                        features['mhoriz_acc'] = np.mean(feature_most_idle['horiz_acc'].fillna(0))
                        features['mvert_acc'] = np.mean(feature_most_idle['vert_acc'].fillna(0))
                        features['mtang_acc'] = np.mean(feature_most_idle['tang_acc'].fillna(0))
                        #print(features)
                if count5 == 5:
                    break

            time_difference = xx['timestamp'].diff()
            time_difference = [d for d in time_difference if d < 1000]
            sum_b_100_500 = sum((i > 100 and i < 500) for i in time_difference)
            # sum_g_500 = sum(i >500 for i in time_difference)
            features["stops"] = sum_b_100_500
            #features["greater_than_500"] = sum_g_500
            feature_tmp = generate_features(xx)

            horiz_spd = feature_tmp['horiz_spd'].fillna(0)
            
            vert_spd = feature_tmp['vert_spd'].fillna(0)
            tang_spd = feature_tmp['tang_spd'].fillna(0)
            horiz_acc = feature_tmp['horiz_acc'].fillna(0)
            vert_acc = feature_tmp['vert_acc'].fillna(0)
            tang_acc = feature_tmp['tang_acc'].fillna(0)

            feature_tmp_2 = generate_features(xx.head(20))

            horiz_spd_2 = feature_tmp_2['horiz_spd'].fillna(0)
            vert_spd_2 = feature_tmp_2['vert_spd'].fillna(0)
            tang_spd_2 = feature_tmp_2['tang_spd'].fillna(0)
            horiz_acc_2 = feature_tmp_2['horiz_acc'].fillna(0)
            vert_acc_2 = feature_tmp_2['vert_acc'].fillna(0)
            tang_acc_2 = feature_tmp_2['tang_acc'].fillna(0)


            #feature_tmp_2_2 = generate_features(xx[:-10])
            feature_tmp_2_2 = generate_features(xx.tail(20))

            horiz_spd_2_l = feature_tmp_2_2['horiz_spd'].fillna(0)
            vert_spd_2_l = feature_tmp_2_2['vert_spd'].fillna(0)
            tang_spd_2_l = feature_tmp_2_2['tang_spd'].fillna(0)
            horiz_acc_2_l = feature_tmp_2_2['horiz_acc'].fillna(0)
            vert_acc_2_l = feature_tmp_2_2['vert_acc'].fillna(0)
            tang_acc_2_l = feature_tmp_2_2['tang_acc'].fillna(0)
            
            # print(horiz_spd.max() - horiz_spd.min())
            # print()
            kk = 0
            #print(click_features[i])
            features['click'] = random.choice(click_features[i])
            #print(np.mean(horiz_spd_2_l))
            features["short_horiz_2_l" +  str(kk)] = np.mean(horiz_spd_2_l)
            features["short_vert_spd_2_l" +   str(kk)] = np.mean(vert_spd_2_l)
            features["short_tang_spd_2_l" +   str(kk)] = np.mean(tang_spd_2_l)
            features["short_horiz_acc_2_l" +   str(kk)] = np.mean(horiz_acc_2_l)
            features["short_vert_acc_2_l" +   str(kk)] = np.mean(vert_acc_2_l)
            features["short_tang_acc_2_l" +   str(kk)] = np.mean(tang_acc_2_l)


            features["short_horiz_2" +  str(kk)] = np.mean(horiz_spd_2)
            features["short_vert_spd_2" +   str(kk)] = np.mean(vert_spd_2)
            features["short_tang_spd_2" +   str(kk)] = np.mean(tang_spd_2)
            features["short_horiz_acc_2" +   str(kk)] = np.mean(horiz_acc_2)
            features["short_vert_acc_2" +   str(kk)] = np.mean(vert_acc_2)
            features["short_tang_acc_2" +   str(kk)] = np.mean(tang_acc_2)

            features['energy_horiz_spd_' + str(kk)] = sum(np.square(horiz_spd))
            if sum(np.square(horiz_spd)) == float("inf"):
                #'mouse_rawx_diff': mouse_raw['x'].diff(), 'mouse_rawx_timestamp': mouse_raw['timestamp'].diff()}
                print("horiz_speed")
                print(horiz_spd)
                print("np squre")
                print(np.square(horiz_spd))
                print("sum")
                print(sum(np.square(horiz_spd)))
                print("timestamp diff")
                print(feature_tmp["mouse_rawx_timestamp"])
                print("mouse_rawx_diff")
                print(feature_tmp["mouse_rawx_diff"])
                
                #print(sum(np.square(horiz_spd)))
            features['energy_vert_spd_' + str(kk)] = sum(np.square(vert_spd))
            features['energy_tang_spd_' + str(kk)] = sum(np.square(tang_spd))
            features['energy_horiz_acc_' + str(kk)] = sum(np.square(horiz_acc))
            features['energy_vert_acc_' + str(kk)] = sum(np.square(vert_acc))
            features['energy_tang_acc_' + str(kk)] = sum(np.square(tang_acc))


            #print(ranges(horiz_spd))
            features['ranges_horiz_spd_' + str(kk)] = ranges(horiz_spd)
            features['ranges_vert_spd_' + str(kk)] = ranges(vert_spd)
            features['ranges_tang_spd_' + str(kk)] = ranges(tang_spd)
            features['ranges_horiz_acc_' + str(kk)] = ranges(horiz_acc)
            features['ranges_vert_acc_' + str(kk)] = ranges(vert_acc)
            features['ranges_tang_acc_' + str(kk)] = ranges(tang_acc)
            # if kk == 8:
            #     features['ranges_tang_spd_' + str(kk)] = ranges(tang_spd)
            #     print(features['ranges_tang_spd_' + str(kk)])
            #     print('ranges_tang_spd_' + str(kk))

            features['rmssd_horiz_spd_' + str(kk)] = rmssd(horiz_spd)
            features['rmssd_vert_spd_' + str(kk)] = rmssd(vert_spd)
            features['rmssd_tang_spd_' + str(kk)] = rmssd(tang_spd)
            features['rmssd_horiz_acc_' + str(kk)] = rmssd(horiz_acc)
            features['rmssd_vert_acc_' + str(kk)] = rmssd(vert_acc)
            features['rmssd_tang_acc_' + str(kk)] = rmssd(tang_acc)
            # # test.append(features)
            # features['sdsd_horiz_spd_' + str(kk)] = sdsd(horiz_spd)
            # features['sdsd_vert_spd_' + str(kk)] = sdsd(vert_spd)
            # features['sdsd_tang_spd_' + str(kk)] = sdsd(tang_spd)
            # features['sdsd_horiz_acc_' + str(kk)] = sdsd(horiz_acc)
            # features['sdsd_vert_acc_' + str(kk)] = sdsd(vert_acc)
            # features['sdsd_tang_acc_' + str(kk)] = sdsd(tang_acc)
            
            features['abs_sum_diff_horiz_spd_' + str(kk)] =   abs_sum_diff(horiz_spd)
            features['abs_sum_diff_vert_spd_' + str(kk)] =   abs_sum_diff(vert_spd)
            features['abs_sum_diff_tang_spd_' + str(kk)] =   abs_sum_diff(tang_spd)
            features['abs_sum_diff_horiz_acc_' + str(kk)] =   abs_sum_diff(horiz_acc)
            features['abs_sum_diff_vert_acc_' + str(kk)] =   abs_sum_diff(vert_acc)
            features['abs_sum_diff_tang_acc_' + str(kk)] =   abs_sum_diff(tang_acc)

            #features['click_' + str(kk)] = random.choice(click_features[i])




        #print(features)
        #print()
            features_array.append(features)

            #     return { 'horiz_spd': horiz_spd, 'vert_spd': vert_spd, 'tang_spd':tang_spd, 
            # 'horiz_acc': horiz_acc, 'vert_acc': vert_acc,  
            # 'tang_acc': tang_acc}


            #plt.scatter(tt['x'].iloc[-1], tt['y'].iloc[-1])
            # plt.scatter(tt['x'], tt['y'])
            # plt.show()
                # for o in range(0, len(tt['x'])):
                #     plt.scatter(tt['x'][:o], tt['y'][:o])
                #     plt.show()
        #x = tt['x']
        #y = tt['y']

        
        #for u in range(0, len(x)):
        # plt.scatter(x, y)
        # plt.show()
df_train = pd.DataFrame(features_array)
train = df_train.copy()
na_sum = train.isna().sum().sum()
which_na = train.isna().any()
which_inf = train.isin([np.inf, -np.inf]).any()

#print(na_sum)
#print(which_na)
#print(which_inf)




donottouch = train.copy()

train = donottouch.copy()

from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import GridSearchCV, StratifiedShuffleSplit
from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from scipy.special import entr
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler
all_acc_mean = []
mouse_result_dataframe_total = pd.DataFrame()
for i in list(donottouch["user"].unique()):
    mouse_result_dataframe = pd.DataFrame()
    train = donottouch.copy()
    
    # train["user"] = train_tmp["user"]
    print("----")
    print(i)
    this_user = train[train["user"] == i]
    
    not_this_user = train[train["user"] != i]
    not_this_user = shuffle(not_this_user, random_state=20)[:len(this_user)]
    # print("This is attackers")
    # print(not_this_user)
    # print("----")
    train = pd.concat([this_user, not_this_user])



    # X_new1 = train.copy()                                        # Create duplicate of data
    # X_new1.replace([np.inf, - np.inf], np.nan, inplace = True)
    # train=X_new1.dropna()



    train.loc[train["user"] != i, "user"] = "Attacker"

    #train = train.dropna()
    # print(train["user"])
    Y =  train.loc[:,'user']
    Y = (Y == "Attacker").astype(int)
    
    # print("This is Y")
    # print(Y)
    X = train.loc[:, train.columns != 'user']


    # highest_non_inf = X.max().loc[lambda v: v<np.Inf].max()
    # X.replace(np.Inf, highest_non_inf)

    # highest_non_inf_n = X.min().loc[lambda v: v>np.Inf].min()
    # X.replace(-np.Inf, highest_non_inf_n)

    scaler = StandardScaler()
    # try:
    X = scaler.fit_transform(X)
    # except:
    #     print(X)
    #which_inf = X.isna().any()
    #print(which_inf)

    X = preprocessing.normalize(X)

    
    x_train,x_val,y_train,y_val = train_test_split(X,Y, test_size = 0.3, random_state=42, stratify=Y)
    X_train,X_val,Y_train,Y_val = train_test_split(X,Y, test_size = 0.3, random_state=42, stratify=Y)   
    print("len(y_val)")
    print(len(y_val))
    # print("Train Y labels:")  
    # print(Y_train.value_counts())
    # print("+")
    # print("Test Y labels: ")
    # print(Y_val.value_counts())
    # print("this is y_val")
    # print(y_val)

    # xgb_clf = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
    #         colsample_bynode=1, colsample_bytree=0.8,
    #         enable_categorical=False, gamma=0, gpu_id=0,
    #         importance_type=None, interaction_constraints='',
    #         learning_rate=0.1, max_delta_step=0, max_depth=4, use_label_encoder=False,
    #         min_child_weight=3, missing=np.nan,
    #         n_estimators=250, n_jobs=-1, nthread=4, num_class=21,
    #         num_parallel_tree=1, objective='multi:softmax',
    #         random_state=27, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
    #         seed=27, subsample=0.8, tree_method='exact', verbosity=0, silent=True)
    xgb_clf = XGBClassifier()

    from sklearn.ensemble import RandomForestClassifier
    



    
    # Define the hyperparameter space to search over
    param_distributions = {
        'n_estimators': [10, 50, 100, 200],
        'max_depth': [2, 4, 6, 8],
        'learning_rate': [0.01, 0.1, 0.2, 0.3],
        'subsample': [0.5, 0.7, 0.9],
        'colsample_bytree': [0.5, 0.7, 0.9],
        'gamma': [0, 1, 5],
        'min_child_weight': [1, 5, 10],
    }

    # Create an XGBClassifier
    xgbc = XGBClassifier()

    # Create a randomized search object
  #  model = RandomizedSearchCV(
    #    xgbc, param_distributions, n_iter=50, cv=5, random_state=42)

    # Fit the randomized search object to the data
    #random_search.fit(X, y)

    # Print the best combination of hyperparameters
   # print('Best hyperparameters:', model.best_params_)



    #Create a Gaussian Classifier
    #xgb_clf=RandomForestClassifier()

    # test the model for our validation data and see the accuracy of the model and how many mislabeled classes are there
    model = xgbc.fit(X_train, Y_train)
    model.save_model(i + "_mouse.bin")
    
    Y_pred = model.predict(X_val)
    y_val_classes = np.where(y_val == 1, i, "Attacker")

    mouse_result_dataframe['true_labels'] = y_val_classes
    mouse_result_dataframe['current'] = i
    mouse_result_dataframe['probabilities'] = list(model.predict_proba(x_val)[:, 1])
    mouse_result_dataframe_total = pd.concat([mouse_result_dataframe, mouse_result_dataframe_total])

    # print(Y_pred)
    # print("Number of mislabeled points out of a total %d points : %d" % (X_val.shape[0], (Y_val != Y_pred).sum()))
    # print(Y_pred[(Y_val != Y_pred)])
    # print(Y_val[(Y_val != Y_pred)])
    total_0 = total_0 + X_val.shape[0]
    diff = diff + (Y_val != Y_pred).sum()
    cm = confusion_matrix(y_val,Y_pred)
    print(cm)
    
    Accuracy = accuracy_score(Y_val,Y_pred)
    print(round(Accuracy*100,2))
    all_acc_mean.append(round(Accuracy*100,2))
    print("----")

print("total: ")
print(total_0)
print("diff")
print(diff)
print(np.mean(all_acc_mean))
#total_array.append(np.mean(all_acc_mean))

----
1
len(y_val)
1490
[[676  69]
 [ 82 663]]
89.87
----
----
10
len(y_val)
1754
[[608 269]
 [279 598]]
68.76
----
----
11
len(y_val)
2478
[[953 286]
 [332 907]]
75.06
----
----
12
len(y_val)
394
[[148  49]
 [ 42 155]]
76.9
----
----
13
len(y_val)
1755
[[678 200]
 [267 610]]
73.39
----
----
14
len(y_val)
1791
[[633 263]
 [270 625]]
70.24
----
----
15
len(y_val)
833
[[364  53]
 [ 71 345]]
85.11
----
----
16
len(y_val)
599
[[254  46]
 [ 57 242]]
82.8
----
----
17
len(y_val)
1169
[[525  60]
 [ 66 518]]
89.22
----
----
18
len(y_val)
8
[[1 3]
 [1 3]]
50.0
----
----
19
len(y_val)
693
[[284  63]
 [ 59 287]]
82.4
----
----
2
len(y_val)
1250
[[543  82]
 [101 524]]
85.36
----
----
3
len(y_val)
2625
[[1111  202]
 [ 233 1079]]
83.43
----
----
4
len(y_val)
2627
[[1043  271]
 [ 288 1025]]
78.72
----
----
5
len(y_val)
476
[[187  51]
 [ 46 192]]
79.62
----
----
6
len(y_val)
186
[[80 13]
 [18 75]]
83.33
----
----
7
len(y_val)
430
[[149  66]
 [ 65 150]]
69.53
----
----
8
len(y_val)
1599
[[665 135]
 [146

In [19]:
#int(tmpp['client_timestamp'].str.split('.')[i][0])*1000 + int(tmpp['client_timestamp'].str.split('.')[i][1])


In [ ]:
total_array = []
for i in movement:
    for k in movement[i]:
        tt = pd.DataFrame(k, columns=tmpp.columns)
        tt = tt[tt['state'] == 'Move']
        proper_a = []
        a = [d for _, d in tt.groupby(tt.index - np.arange(len(tt)))]
        for u in a:
            if 200 < len(u) < 500:
                proper_a.append(u)
        for xx in proper_a:
            features = {'user': i}
            xx = xx.drop_duplicates(subset='timestamp', keep='first').astype({'x': int, 'y': int, 'timestamp': int})
            b = tt['timestamp'].diff().fillna(0)
            ind = np.argpartition(b, -len(b))[-len(b):]
            for yuy in ind:
                if len(features) >= 7:
                    break
                if 0 < len(xx[yuy:yuy+10]) <= 10:
                    feature_most_idle = generate_features(xx[yuy:yuy+10])
                    features['mhoriz_spd'] = np.mean(feature_most_idle['horiz_spd'].fillna(0))
                    features['mvert_spd'] = np.mean(feature_most_idle['vert_spd'].fillna(0))
                    features['mtang_spd'] = np.mean(feature_most_idle['tang_spd'].fillna(0))
                    features['mhoriz_acc'] = np.mean(feature_most_idle['horiz_acc'].fillna(0))
                    features['mvert_acc'] = np.mean(feature_most_idle['vert_acc'].fillna(0))
                    features['mtang_acc'] = np.mean(feature_most_idle['tang_acc'].fillna(0))
                time_difference = xx['timestamp'].diff()
                time_difference = time_difference[time_difference < 1000]
                features['stops'] = (100 < time_difference) & (time_difference < 500)
            feature_tmp = generate_features(xx)
            feature_tmp_2 = generate_features(xx.head(20))
            feature_tmp_2_2 = generate_features(xx.tail(20))
            for feature_name in ['horiz_spd', 'vert_spd', 'tang_spd', 'horiz_acc', 'vert_acc', 'tang_acc']:
                for feature in [feature_tmp, feature_tmp_2, feature_tmp_2_2]:
                    features[feature_name + '_max'] = feature[feature_name].max()
                    features[feature_name + '_min'] = feature[feature_name].min()
                    features[feature_name + '_mean'] = feature[feature_name].mean()
            total_array.append(features)